### PR TITLE
Added problem solution of Short Substrings Codeforces 

### PR DESCRIPTION
**Pull request by ayush179**
The problem is a very popular one where we are dealing with 2 substrings a & b-

b is built from a as follows: write all the substrings of length 2 of the string a in the order from left to right, and then join them in the same order into the string b.

For example, if we come up with the string a="abac", then all the substrings of length 2 of the string a are: "ab", "ba", "ac". Therefore, the string b="abbaac".

Now, what the code does? We are given the string b and we have to find the parent string a. It can work on any number of test cases t. Given below are some test cases.
INPUT-
4
abbaac
ac
bccddaaf
zzzzzzzzzz
OUTPUT-
abac
ac
bcdaf
zzzzzz

### CODE REVIEW

**Comment by sansyrox** [comment]
@ayush179 , this looks really good. Can you add some comments on the top of the file denoting its purpose?

**Comment by ayush179** [comment]
Yes sure
Thanks

**Comment by ayush179** [comment]
@sansyrox , have a look and let me know if any changes are to be made?

**Review by sansyrox — APPROVED** [review]
@ayush179 , this looks good 🔥 . Merging this!

**Comment by ayush179** [comment]
hey @sansyrox can you add hactoberfest-accepted label to this contribution as per the updated rules of hactober or it may be declared insignificant?
Thanks

**Comment by sansyrox** [comment]
Done @ayush179

**Pull request merged**
