### PR TITLE
Added A* path finding algorithm in python

### PR DESCRIPTION
**Pull request by sairajchouhan**
A* pathfinding algorithm - arguably the best pathfinding algorithm; uses heuristics to guarantee the shortest path much faster than Dijkstra's Algorithm

### CODE REVIEW

**Comment by sairajchouhan** [comment]
hey @sansyrox checkout the algorithm make sure you merge to master if you find some value out of it

**Comment by sansyrox** [comment]
@sairaj2119 , this looks really good. Can you add some comments on the top of the file to describe its purpose?

**Comment by sairajchouhan** [comment]
Yeah...sure

**Comment by sairajchouhan** [comment]
hey @sansyrox  I did my best to explain the algorithm in the simplest way check it out 😁

**Comment by sansyrox** [comment]
Great Job @sairaj2119 🔥 . Merging it

**Pull request merged**
