### PR TITLE
6 sorting algorithms in python added

### PR DESCRIPTION
**Pull request by KickItLikeShika**
Bubble sort, insertion sort, merge sort, quick sort, counting sort, heap sort

### CODE REVIEW

**Comment by sansyrox** [comment]
@KickItLikeShika , this looks really good. 

Can you add a doc string in the top of the file.

eg. for the bubble sort file

```
This file contains the Bubble Sort Algorithm written in python.

<and then the code here>

```

**Comment by KickItLikeShika** [comment]
@sansyrox It's done. Review my pull request please.

**Comment by sansyrox** [comment]
Alrighttttt. Good job @KickItLikeShika 🔥 🔥

**Review by sansyrox — APPROVED** [review]

**Comment by KickItLikeShika** [comment]
@sansyrox Hey sansyrox, can you label my pull request as hacktoberfest-accepted?

**Pull request merged**
